FROM ibmcom/powerai:1.6.0-all-ubuntu18.04-py3

ENV USER_NAME pwrai
ENV WORK_DIR /home/${USER_NAME}/microDL

ENV PATH /opt/anaconda3/bin/pip:/opt/anaconda3/bin/python:${PATH} 
#/root/.local/bin:${PATH}

RUN ["/bin/bash", "-c", "cd /opt/anaconda3/bin && source activate base && IBM_POWERAI_LICENSE_ACCEPT=yes ./accept-powerai-license.sh" ]

RUN sudo /bin/ln -sf /bin/bash /bin/sh
#RUN sudo /bin/sed -i -e "/ddl-tensorflow/a\

# Tools
RUN apt-get update && apt-get install -y \
 software-properties-common && \
 add-apt-repository universe
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections \
&& sudo apt-get update && sudo apt-get install -yq --no-install-recommends \
         build-essential \
         apt-utils \
         libcupti-dev \
         ca-certificates \
         cmake \
         libfreetype6-dev \
         libpng-dev \
         wget \
         git \
         pkg-config \
         tmux \
         graphviz \
         vim
         #python3-pip
         #python3-dev \
         #python3-distutils \
         #python3-venv

# Cleanup
RUN sudo apt-get clean && \
sudo apt-get autoremove && \
sudo rm -rf /var/lib/apt/lists/*

ADD requirements_docker.txt /tmp/requirements.txt
#RUN echo $PATH
#RUN wget https://bootstrap.pypa.io/pip/3.6/get-pip.py && \
#    python3.6 get-pip.py --target $(python3.6 -c 'import sys; print(sys.path[-1])') && \
#    rm get-pip.py && \


#RUN python3 -m venv env && source ./env/bin/activate && \
RUN sudo pip install --upgrade --force pip setuptools wheel && \
#pip install --upgrade Cython==0.29.10 && \
#pip3 install --upgrade numpy && \
#pip3 install --upgrade scipy && \
#pip3 install --upgrade scikit-image && \
#pip3 install --upgrade scikit-learn && \
#pip3 install --upgrade opencv-python && \
#pip3 install --upgrade pandas && \
#pip3 install --upgrade natsort nose protobuf pydot PyYAML testfixtures tqdm zarr && \
# Install pip packages from requirements text file
pip install --user --upgrade -r /tmp/requirements.txt && \
pip install --upgrade --no-cache-dir keras==2.1.6 && \
# Jupyter
pip install --upgrade --no-cache-dir jupyter
#pip install --upgrade matplotlib

WORKDIR ${WORK_DIR}
ENV PYTHONPATH ${WORK_DIR}
#RUN sudo chown ${USER_NAME} ${WORK_DIR}
#RUN sudo chgrp ${USER_NAME} ${WORK_DIR}

EXPOSE 8888 6006
