FROM ibmcom/powerai:1.6.0-all-ubuntu18.04-py3

ENV USER_NAME pwrai
#ENV CONDA_DIR /home/pwrai/anaconda3
#ENV PATH ${CONDA_DIR}/bin:${PATH}
ENV WORK_DIR /home/${USER_NAME}/microDL


RUN ["/bin/bash", "-c", "cd /opt/anaconda3/bin && source activate base && IBM_POWERAI_LICENSE_ACCEPT=yes ./accept-powerai-license.sh" ]

#RUN echo 1 | sudo /opt/anaconda3/bin/accept-powerai-license.sh
RUN sudo /bin/ln -sf /bin/bash /bin/sh
#RUN sudo /bin/sed -i -e "/ddl-tensorflow/a\
#\ \ \ \ scripts['tensorboard']=\'/opt/DL/tensorboard/bin/tensorboard-activate\'" /var/local/powerai/default_framework.sh
RUN echo which python3
# Tools
# RUN sudo apt-get update && sudo apt-get install -yq --no-install-recommends \
RUN apt-get update && apt-get install -y \
 software-properties-common && \
 add-apt-repository universe
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections \
&& sudo apt-get update && sudo apt-get install -yq --no-install-recommends \
         build-essential \
         apt-utils \
         libcupti-dev \
         ca-certificates \
         cmake \
         libfreetype6-dev \
         wget \
         git \
         pkg-config \
         tmux \
         graphviz \
         vim 

# Cleanup
RUN sudo apt-get clean && \
sudo apt-get autoremove && \
sudo rm -rf /var/lib/apt/lists/*

ENV PATH /opt/anaconda3/bin:${PATH}
RUN sudo ln -s /opt/anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh
ADD conda_environment_docker.yml /tmp/conda.yml
RUN conda update -n base -c defaults --override-channels conda && \
conda env create --file=/tmp/conda.yml && \
#conda env update --name base --prune --file=/tmp/conda.yml && \
#conda install tensorflow-gpu==1.13.1 && \
conda activate micro_dl


WORKDIR ${WORK_DIR}
ENV PYTHONPATH ${WORK_DIR}
RUN sudo chown ${USER_NAME} ${WORK_DIR}
RUN sudo chgrp ${USER_NAME} ${WORK_DIR}

EXPOSE 8888 6006
