model_dir: '/Users/jenny.folkesson/data/microglia_newsegm/'
image_dir: '/Volumes/MicroscopyData/imaging_group/ucsf_microglia/UCSF-2018-05-04-00-00-00-0001/'
data_split: 'test'
image_params_dict:
    image_format: 'zyx'
    im_ext: '.png'
metrics: ['r2', 'corr', 'ssim']
metrics_orientations: ['xy']