output_dir: '/data/xyz'
verbose: 10
input_dir: '/data/abc'
slice_ids: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
pos_ids: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 25, 26, 28, 34, 39]
channel_ids: [1, 7]
num_workers: 4
resize:
    scale_factor: [4.85, 1.0, 1.0]
    num_slices_subvolume: 10
correct_flat_field: False
uniform_structure: True
masks:
    channels: [5]
    str_elem_radius: 3
tile:
    tile_size: [256, 256]
    step_size: [128, 128]
    depths: [3, 3, 1]
    mask_depth: 3
    image_format: 'zyx'
    save_tiled_masks: True
    min_fraction: 0.25