base_output_dir: '/Users/jenny.folkesson//Data/debug_lif'
focal_plane_idx: 0
verbose: 10
split_volumes: True
splitter_class: LifStackSplitter2D
input_fname: '/Users/jenny.folkesson/Data/BlankSlide_DAPI_TxRed_BF_Phase.lif'
correct_flat_field: True
flat_field_class: FlatFieldEstimator2D
use_masks: True
masks:
    mask_channels: [0, 1]
    str_elem_radius: 3
tile_stack: True
tile:
    channels: -1
    tile_size: [256, 256]
    step_size: [64, 64]
    save_cropped_masks: True
    min_fraction: 0.15
    hist_clip_limits: [2, 98]