dataset:
    data_dir: '/Users/jenny.folkesson/Data/SMS-2018-07-03-18-35-00-0010_train_data'
    tiles_steps: 'tiles_256-256_step_64-64'
    input_channels: [0]
    target_channels: [5]
    mask_channels: [5]
    split_by_column: slice_idx
    split_ratio:
        train: 0.6
        val: 0.2
        test: 0.2
    height: 256
    width: 256
verbose: 10
trainer:
    output_type: 'continuous'
    model_dir: '/Users/jenny.folkesson/Data/models/refactor_labelfree_bs16_mse'
    batch_size: 16
    max_epochs: 50
    patience: 20
    masked_loss: False
    metrics: mask_coeff_determination
    loss: mean_squared_error
    callbacks:
        LearningRateScheduler:
            lr_find: False
            base_lr: 0.001
            max_lr: 0.01
            step_size: 2
            gamma: 0.999
            scale_mode: iterations
        EarlyStopping:
            mode: min
            monitor: val_loss
            patience: 40
            verbose: True
        ModelCheckpoint:
            mode: min
            monitor: val_loss
            save_best_only: True
            verbose: True
        TensorBoard:
            histogram_freq: 0
            verbose: True
    optimizer:
        lr: 0.001
        name: Nadam
network:
    class: UNet2D
    num_filters_per_block: [16, 32, 64, 96, 128]
    num_convs_per_block: 2
    filter_size: 3
    batch_norm: True
    activation: relu
    pooling_type: mean
    skip_merge_type: concat
    upsampling: nearest_neighbor
    dropout: 0.3
    residual: True
    height: 256
    width: 256
    num_input_channels: 1
    num_target_channels: 1
    data_format: 'channels_first'
    final_activation: linear
