output_dir: '/Users/jenny.folkesson/Data/SMS-2018-07-03-18-35-00-0010_train_data'
focal_plane_idx: 0
verbose: 10
split_volumes: False
splitter_class: None
input_dir: '/Users/jenny.folkesson/Data/SMS-2018-07-03-18-35-00-0010'
correct_flat_field: True
flat_field_class: FlatFieldEstimator2D
use_masks: True
masks:
    mask_channels: [5]
    str_elem_radius: 3
tile_stack: True
tile:
    channels: -1
    tile_size: [256, 256]
    step_size: [64, 64]
    save_cropped_masks: True
    min_fraction: 0.15
    hist_clip_limits: [2, 98]