zarr_dir: /hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_A549_2023_02_07/Input_Nucl/A549_20X.zarr
dataset:
  input_channels: [2]
  target_channels: [3]
  window_size: [5,256,256]
  normalization:
    scheme: 'FOV'
    type: 'median_and_iqr'
  min_foreground_fraction: 0.02
  mask_type: 'otsu'
  flatfield_correct: False
  batch_size: 8
  split_ratio: 
    test: 0.1
    train: 0.8
    val: 0.1
  use_recorded_data_split: false

model:
  architecture: 2.5D
  in_channels: 1
  out_channels: 1 #this can just be automated from dataset config
  in_stack_depth: 5
  residual: true
  task: reg

preprocessing:
  flatfield:
    channel_ids: [3]
    slice_ids: -1
    block_size: 32
  normalize:
    channel_ids: [3]
    block_size: 32
    scheme: "FOV"
    num_workers: 8
  masks:
    channel_ids: [3]
    time_ids: -1
    slice_ids: -1
    thresholding_type: "otsu"
    output_channel: none
    structuring_element_radius: 5
    num_workers: 8
training:
  epochs: 20
  samples_per_epoch: 100
  learning_rate: 0.0001
  optimizer: adam
  loss: mae
  testing_stride: 1
  save_model_stride: 1
  save_dir: '/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_A549_2023_02_07/model_nucl25d/2023_02_gpTest/'
  device: 'gpu'
  num_workers: 8
  augmentations:
    transpose:
      transpose_only: [1,2] #spatial dimensions: 0:z, 1:y, 2:x
    mirror: 
      mirror_only: [1,2] #spatial dimensions: 0:z, 1:y, 2:x
    rotate: 
      rotation_interval: [0,3.14]
    zoom:
      scale_interval: [0.5,1.5]
    blur:
      mode: 'gaussian'
      width_range: [3,15]
      sigma: 0.1
      prob: 0.2
      blur_channels: [2]
    shear:
      angle_range: [-15,15]
      prob: 0.2
      shear_middle_slice_only: [0,2]
    intensity_jitter:
      scale_range: [0.5, 1.5]
      shift_range: [-0.15, 0.15]
      norm_before_shift: True
      jitter_demeaned: True
      prob: 0.2
      jitter_channels: [2]
    noise:
      mode: 'gaussian'
      seed: 14156
      clip: True
      prob: 0.2
      noise_channels: [2]

inference:
  z_slice_range: [0, 7]
  window_size: [5, 2000, 2000]
  model_dir: '/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_A549_2023_02_07/model_nucl25d/2023_02_gpTest/training_model_2023_02_28_13_09/saved_model_ep_7_testloss_5.3496.pt'
  save_preds_to_model_dir: True
  custom_save_preds_dir: None
  data_partition_to_predict: val
  device: 'gpu'
  image_format: 'zyx'

evaluation_metrics:
  cp_model: 'CP_20220915_A549Mem' # cellpose model for segmentation
  ground_truth_dir: None # None:if dir is generated during inference inside model dir
  metrics: ['ssim','r2','corr','IoU', 'VI', 'POD']
  mask_ext: '_cp_mask.png'