zarr_dir: /hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_VeroA549_2022_12_14/Inputs_nucl/A549_20X.zarr
dataset:
  input_channels: [1]
  target_channels: [0]
  window_size: [5,256,256]
  normalization:
    scheme: 'FOV'
    type: 'median_and_iqr'
  min_foreground_fraction: 0.1
  mask_type: 'unimodal'
  flatfield_correct: True
  batch_size: 64
  split_ratio: 
    test: 0.08
    train: 0.85
    val: 0.07
model:
  architecture: 2.5D
  in_channels: 1
  out_channels: 1 #this can just be automated from dataset config
  in_stack_depth: 5
  residual: true
  task: reg
  model_dir: '/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_VeroA549_2022_12_14/model_2d/2023_01_gunpowder_test/training_model_2023_01_03_13_58/saved_model_ep_9_testloss_0.9924.pt'
preprocessing:
  flatfield:
    channel_ids: -1
    slice_ids: -1
    block_size: 32
  normalize:
    channel_ids: -1
    block_size: 32
    scheme: "FOV"
    num_workers: 8
  masks:
    channel_ids: -1
    time_ids: -1
    slice_ids: -1
    thresholding_type: "unimodal"
    output_channel: none
    structuring_element_radius: 1
    num_workers: 8
training:
  epochs: 10
  samples_per_epoch: 300
  learning_rate: 0.0015
  optimizer: adam
  loss: mae
  testing_stride: 1
  save_model_stride: 1
  save_dir: '/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_VeroA549_2022_12_14/model_2d/2023_01_gunpowder_test/'
  device: 'gpu'
  num_workers: 16
  augmentations:
    transpose:
      transpose_only: [1,2] #spatial dimensions: 0:z, 1:y, 2:x
    mirror: 
      mirror_only: [1,2] #spatial dimensions: 0:z, 1:y, 2:x
    rotate: 
      rotation_interval: [0,3.14]
    zoom:
      scale_interval: [0.7,1.3]
    blur:
      mode: 'gaussian'
      width_range: [3,7]
      sigma: 0.1
      prob: 0.2
      blur_channels: [1]
    shear:
      angle_range: [-15,15]
      prob: 0.2
      shear_middle_slice_only: [0,2]
    intensity_jitter:
      scale_range: [0.7, 1.3]
      shift_range: [-0.15, 0.15]
      norm_before_shift: True
      jitter_demeaned: True
      prob: 0.2
      jitter_channels: [1]
    noise:
      mode: 'gaussian'
      seed: 14156
      clip: True
      prob: 0.2
      noise_channels: [1]
data_split: all
images:
    image_format: 'zyx'
    image_ext: '.tif'
    name_format: sms
    pred_chan_name: 'pred'
save_figs: True
metrics:
    metrics: ['r2', 'corr', 'mse', 'mae']
    metrics_orientations: ['xy']
    binarize_model: ['CP_20220902_NuclFL']
    targetmask_dir: '/hpc/projects/CompMicro/projects/infected_cell_imaging/VirtualStaining/VirtualStain_NuclMem_VeroA549_2022_12_14/Inputs_nucl/TargetMask_A549/'
